apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: grafanadashboards.lunarway.com
spec:
  group: lunarway.com
  names:
    kind: GrafanaDashboard
    listKind: GrafanaDashboardList
    plural: grafanadashboards
    singular: grafanadashboard
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          description: GrafanaDashboard is the Schema for the grafanadashboards API
          properties:
            apiVersion:
              type: string
            kind:
              type: string
            metadata:
              type: object
            spec:
              description: GrafanaDashboardSpec defines the desired state of GrafanaDashboard
              properties:
                folderTitle:
                  type: string
                json:
                  type: string
                name:
                  type: string
              required:
                - json
                - name
              type: object
          type: object
      subresources:
        status: {}
